model:
  temperature: 0.1
  top_p: 0.9
  
embeddings:
  model_name: "nomic-embed-text-v2-moe:latest"

rag:
  k_retrieval: 6
  vector_size: 768
  distance_metric: "COSINE"
paths:
  clean_data: "data/celsia_knowledge_base_clean"
  markdown_data: "data/celsia_knowledge_base_markdown"
  basic_info_json: "data/documents/basic_information.json"